- name: Check Deluge Installed
  package_facts:
    manager: auto

- name: Create Dir for packages
  file:
    path: "{{ local_home }}/deluge"
    state: directory
  when: "'deluge' not in ansible_facts.packages"

- name: Download Deluge packages (legacy versions)
  get_url:
    url: "{{ item }}"
    dest: "{{ local_home }}/deluge"
  loop:
    -  http://archive.ubuntu.com/ubuntu/pool/universe/libt/libtorrent-rasterbar/python-libtorrent_1.1.5-1build1_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/libt/libtorrent-rasterbar/libtorrent-rasterbar9_1.1.5-1build1_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.65.1/libboost-system1.65.1_1.65.1+dfsg-0ubuntu5_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/b/boost1.65.1/libboost-python1.65.1_1.65.1+dfsg-0ubuntu5_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-common_1.3.15-2_all.deb
    -  http://security.ubuntu.com/ubuntu/pool/main/t/twisted/python-twisted-core_17.9.0-2ubuntu0.1_all.deb
    -  http://security.ubuntu.com/ubuntu/pool/main/t/twisted/python-twisted-bin_17.9.0-2ubuntu0.1_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/main/i/incremental/python-incremental_16.10.1-3_all.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-glade2_2.24.0-5.1ubuntu2_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/p/pygtk/python-gtk2_2.24.0-5.1ubuntu2_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/n/notify-python/python-notify_0.1.1-4_amd64.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-common_1.3.15-2_all.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge-gtk_1.3.15-2_all.deb
    -  http://archive.ubuntu.com/ubuntu/pool/universe/d/deluge/deluge_1.3.15-2_all.deb
  when: "'deluge' not in ansible_facts.packages"

  #- name: Find Deluge Packages to Install
  #find:
  #path: "{{ local_home }}/deluge/"
  #patterns: '*.deb'
  #register: result
  #when: "'deluge' not in ansible_facts.packages"

  #- name: Install Deluge Packages
  #apt:
  #deb: "{{ item }}"
  #loop:
  #become: yes
  #when: "'deluge' not in ansible_facts.packages"

- name: Install Deluge Packages
  become: yes
  shell: 
    cmd: apt-get -y install ./*.deb
    chdir: "{{ local_home }}/deluge"
    warn: no
  when: "'deluge' not in ansible_facts.packages"

- name: Pin Deluge
  copy: 
    dest: /etc/apt/preferences.d/pin-deluge
    content: |
      Package: deluge
      Pin: version 1.3.15-2
      Pin-Priority: 1337

      Package: deluge-common
      Pin: version 1.3.15-2
      Pin-Priority: 1337

      Package: deluge-gtk
      Pin: version 1.3.15-2
      Pin-Priority: 1337

      Package: libtorrent-rasterbar9
      Pin: version 1.1.5-1build1
      Pin-Priority: 1337
  become: yes

- name: Remove Dir for packages
  file:
    path: "{{ local_home }}/deluge"
    state: absent

