- name: Mount additional disks
  become: yes
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    dump: 0
    passno: 2
    state: mounted
    backup: yes
  with_items:
    - { src: UUID=d3b25800-0583-4f28-b78b-b33d79f2b55a, path: /mnt/gradok }
    - { src: UUID=2ae8b2d2-e6f0-42f2-b16a-5b8ab8a11ee2, path: /mnt/jiangyin }
    - { src: UUID=a96384c1-bb8e-4381-b4eb-0a9c0dff5233, path: /mnt/vadim }
  when: local_machine == "klaus"

