- name: Clone dotfiles
  git:
    repo: "git@github.com:besnef/dotfiles.git"
    dest: "{{ local_repo_dir }}/dotfiles"
    accept_hostkey: yes
    update: no

- name: Run DotBot install 
  shell: 
    cmd: ./install home
    chdir: "{{ local_repo_dir }}/dotfiles"

