- hosts: localhost
  vars:
    local_user: "{{ ansible_user_id }}"
    local_home: "{{ lookup('env','HOME')  }}"
    local_machine: "{{ ansible_facts.nodename }}"
  vars_files:
    - vars/external_vars.yml

  roles:
    - {role: environment, tags: 'env'}
    - {role: dotfiles, tags: 'dotfiles'}
    - {role: github, tags: 'github'}
    - {role: zsh, tags: 'zsh'}
    - {role: vim, tags: 'vim'}
    - {role: dconf, tags: 'dconf'}
    - {role: gnome_tweaks, tags: 'gnome'}
    - {role: guake, tags: 'guake'}
    - {role: chrome, tags: 'chrome'}
    - {role: vscode, tags: 'vscode'}
    - {role: calibre, tags: 'calibre'}
    - {role: mcomix, tags: 'mcomix'}

