  - name: install deluge ppa
    apt_repository:
      repo: ppa:deluge-team/stable
      state: present
    become: yes

  - name: install deluge-gtk
    apt:
      name: deluge-gtk
      update_cache: yes
      state: latest
    become: yes
